In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
dataset["classification_yes"].value_counts()
#refer how many class classified
#to find balanced or imbalanced
#unique entry &counts---->(0-143,1-143)->balanced
#(0-257,1-143)->imbalanced

1    249
0    150
Name: classification_yes, dtype: int64

In [7]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [8]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', ]]
dep=dataset["classification_yes"]

In [9]:
indep.shape#400-length ,3-i/p column

(399, 27)

In [10]:
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: uint8

In [11]:
#split into training & test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [12]:
#replace regression to classifier for classification
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
param_grid={'criterion':['gini', 'entropy', 'log_loss'],'splitter':['best', 'random']}
grid=GridSearchCV(DecisionTreeClassifier(),param_grid,refit=True,verbose=3,n_jobs=1,scoring='f1_weighted')
#f1_weighted suitable for all balanced &imbalance including precision,recall)
#fitting model for grid search
grid.fit(x_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV 1/5] END .....criterion=gini, splitter=best;, score=0.929 total time=   0.0s
[CV 2/5] END .....criterion=gini, splitter=best;, score=0.909 total time=   0.0s
[CV 3/5] END .....criterion=gini, splitter=best;, score=0.895 total time=   0.0s
[CV 4/5] END .....criterion=gini, splitter=best;, score=0.946 total time=   0.0s
[CV 5/5] END .....criterion=gini, splitter=best;, score=0.964 total time=   0.0s
[CV 1/5] END ...criterion=gini, splitter=random;, score=0.964 total time=   0.0s
[CV 2/5] END ...criterion=gini, splitter=random;, score=0.876 total time=   0.0s
[CV 3/5] END ...criterion=gini, splitter=random;, score=0.930 total time=   0.0s
[CV 4/5] END ...criterion=gini, splitter=random;, score=0.964 total time=   0.0s
[CV 5/5] END ...criterion=gini, splitter=random;, score=0.982 total time=   0.0s
[CV 1/5] END ..criterion=entropy, splitter=best;, score=1.000 total time=   0.0s
[CV 2/5] END ..criterion=entropy, splitter=best;, score=0.964 total time=   0.0s
[CV 3/5] END ..criterion=entropy, splitter=best;, score=0.859 total time=   0.0s
[CV 4/5] END ..criterion=entropy, splitter=best;, score=0.909 total time=   0.0s
[CV 5/5] END ..criterion=entropy, splitter=best;, score=0.982 total time=   0.0s
[CV 1/5] END criterion=entropy, splitter=random;, score=0.947 total time=   0.0s
[CV 2/5] END criterion=entropy, splitter=random;, score=0.964 total time=   0.0s
[CV 3/5] END criterion=entropy, splitter=random;, score=0.895 total time=   0.0s
[CV 4/5] END criterion=entropy, splitter=random;, score=0.965 total time=   0.0s
[CV 5/5] END criterion=entropy, splitter=random;, score=0.982 total time=   0.0s
[CV 1/5] END ...criterion=log_loss, splitter=best;, score=nan total time=   0.0s
[CV 2/5] END ...criterion=log_loss, splitter=best;, score=nan total time=   0.0s
[CV 3/5] END ...criterion=log_loss, splitter=best;, score=nan total time=   0.0s
[CV 4/5] END ...criterion=log_loss, splitter=best;, score=nan total time=   0.0s
[CV 5/5] END ...criterion=log_loss, splitter=best;, score=nan total time=   0.0s
[CV 1/5] END .criterion=log_loss, splitter=random;, score=nan total time=   0.0s
[CV 2/5] END .criterion=log_loss, splitter=random;, score=nan total time=   0.0s
[CV 3/5] END .criterion=log_loss, splitter=random;, score=nan total time=   0.0s
[CV 4/5] END .criterion=log_loss, splitter=random;, score=nan total time=   0.0s
[CV 5/5] END .criterion=log_loss, splitter=random;, score=nan total time=   0.0s

C:\anaconda\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning:
10 fits failed out of a total of 30.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\anaconda\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\anaconda\lib\site-packages\sklearn\tree\_classes.py", line 942, in fit
    X_idx_sorted=X_idx_sorted,
  File "C:\anaconda\lib\site-packages\sklearn\tree\_classes.py", line 352, in fit
    criterion = CRITERIA_CLF[self.criterion](
KeyError: 'log_loss'

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\anaconda\lib\site-packages\sklearn\model_selection\_search.py:972: UserWarning: One or more of the test scores are non-finite: [0.92851588 0.94310511 0.94281736 0.9504596         nan        nan]
  category=UserWarning,

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [13]:
#print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
grid_predictions=grid.predict(x_test)

In [14]:
re=grid.cv_results_
print("The value of best parameters{}:".format(grid.best_params_))

The value of best parameters{'criterion': 'entropy', 'splitter': 'random'}:

In [15]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("f1_macro value for best parameter{}:".format(grid.best_params_),f1_macro)#optional

f1_macro value for best parameter{'criterion': 'entropy', 'splitter': 'random'}: 0.9668037602820211

In [16]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)

In [17]:
# 79,0 correct diagonal,41,0 wrong diagonal
#type1 error should low
print(cm)

[[44  1]
 [ 3 72]]

In [18]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)

In [19]:
#overall performance(accuracy)=0.89
print(clf_report)

              precision    recall  f1-score   support

           0       0.94      0.98      0.96        45
           1       0.99      0.96      0.97        75

    accuracy                           0.97       120
   macro avg       0.96      0.97      0.96       120
weighted avg       0.97      0.97      0.97       120

In [20]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])#receiver operating chareteristics area under curve(roc_auc)

0.9688888888888889

In [21]:
table = pd.DataFrame.from_dict(re)

In [22]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003431,0.004217,0.000000,0.000000,gini,best,"{'criterion': 'gini', 'splitter': 'best'}",0.929144,0.909115,0.894531,0.946153,0.963636,0.928516,0.024804,4
1,0.006569,0.006738,0.000677,0.000836,gini,random,"{'criterion': 'gini', 'splitter': 'random'}",0.964286,0.875548,0.929513,0.964286,0.981894,0.943105,0.037817,2
2,0.001342,0.001645,0.003840,0.005891,entropy,best,"{'criterion': 'entropy', 'splitter': 'best'}",1.000000,0.963889,0.859355,0.909115,0.981728,0.942817,0.051633,3
3,0.003126,0.006252,0.000000,0.000000,entropy,random,"{'criterion': 'entropy', 'splitter': 'random'}",0.947015,0.964286,0.894531,0.964572,0.981894,0.950460,0.030061,1
4,0.001539,0.002171,0.000000,0.000000,log_loss,best,"{'criterion': 'log_loss', 'splitter': 'best'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
5,0.002021,0.003101,0.000000,0.000000,log_loss,random,"{'criterion': 'log_loss', 'splitter': 'random'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,6

In [23]:
best = grid.best_score_

In [24]:
best

0.9504595990541148

In [25]:
age=int(input("Age:"))
bp=int(input("bp:"))
al=int(input("al:"))
su=int(input("su:"))
bgr=int(input("bgr:"))
bu=int(input("bu:"))
sc=int(input("sc:"))
sod=int(input("sod:"))
pot=int(input("pot:"))
hrmo=int(input("hrmo:"))
pcv=int(input("pcv:"))
wc=int(input("wc:"))
rc=int(input("rc:"))
sg_b=int(input("sg_b:"))
sg_c=int(input("sg_c:"))
sg_d=int(input("sg_d:"))
sg_e=int(input("sg_e:"))
rbc_normal=int(input("rbc_normal:"))
pc_normal=int(input("pc_normal:"))
pcc_present=int(input("pcc_present:"))
ba_present=int(input("ba_present:"))
htn_yes=int(input("htn_yes:"))
dm_yes=int(input("dm_yes:"))
cad_yes=int(input("cad_yes:"))
appet_yes=int(input("appet_yes:"))
pe_yes=int(input("pe_yes:"))
ane_yes=int(input("ane_yes:"))

Age:1
bp:1
al:1
su:1
bgr:1
bu:11
sc:1
sod:1
pot:1
hrmo:1
pcv:1
wc:1
rc:1
sg_b:1
sg_c:1
sg_d:1
sg_e:1
rbc_normal:1
pc_normal:1
pcc_present:1
ba_present:1
htn_yes:1
dm_yes:1
cad_yes:1
appet_yes:1
pe_yes:1
ane_yes:1

In [26]:
Future_Prediction=grid.predict([[age, bp, al, su, bgr, bu, sc, sod, pot, hrmo,pcv,
       wc, rc, sg_b, sg_c, sg_d, sg_e, rbc_normal, pc_normal,
    pcc_present, ba_present, htn_yes, dm_yes, cad_yes,appet_yes, pe_yes, ane_yes]])
print("Future_Prediction{}".format(Future_Prediction))

Future_Prediction[1]

C:\anaconda\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"

In [27]:
import pickle
filename="finalized_model_Grid.sav"
pickle.dump(grid,open(filename,'wb'))

In [29]:
loaded_model=pickle.load(open("finalized_model_Grid.sav",'rb'))
result=loaded_model.predict([[36,111,23,34,55,66,44,22,22,11,11,222,111,222,112,1,1,1,0,0,0,0,0,1,1,1,1]])

C:\anaconda\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"

In [30]:
result

array([1], dtype=uint8)